global:
  storageClass: 
  clusterDomain: &global-cluster-domain cluster.local


# Please change this to the domain name / IP where OneUptime server is hosted on. 
host: localhost
httpProtocol: http

# (Optional): You usually do not need to set this if you're self hosting. 
openTelemetryCollectorHost: 

volume: 
  certs: 
    storage: 1Gi

deployment: 
  replicaCount: 1

metalLb: 
  enabled: false
  ipAdddressPool: 
    enabled: false
    addresses: 
      # - 51.158.55.153/32

ingress:
  service: 
    type: LoadBalancer
    loadBalancerIP: 

postgresql: 
  clusterDomain: *global-cluster-domain
  auth: 
    username: oneuptime
    database: oneuptimedb
  architecture: standalone
  primary:
    persistence:
      size: 25Gi
  readReplicas: 
    persistence:
      size: 25Gi

clickhouse: 
  clusterDomain: *global-cluster-domain
  shards: 1
  replicaCount: 1
  zookeeper: 
    enabled: false
  persistence: 
    size: 25Gi
  auth: 
    username: oneuptime
  initdbScripts: 
    db-init.sql: |
      CREATE DATABASE oneuptime;

redis: 
  clusterDomain: *global-cluster-domain
  architecture: standalone
  auth:
    enabled: true
  master:
    persistence:
      enabled: false # We dont need redis persistence, because we dont do anything with it. 
  replica:
    persistence:
      enabled: false # We dont need redis persistence, because we dont do anything with it. 
  

image:
  registry: docker.io
  repository: oneuptime
  pullPolicy: Always
  tag: release
  restartPolicy: Always

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeEnvironment: production

billing: 
  enabled: false
  publicKey: 
  privateKey: 
  smsDefaultValueInCents: 
  callDefaultValueInCentsPerMinute:
  smsHighRiskValueInCents:
  callHighRiskValueInCentsPerMinute: 

subscriptionPlan: 
  basic: 
  growth: 
  scale: 
  enterprise: 

analytics: 
  host:
  key: 

internalSmtp: 
  sendingDomain: 
  dkimPrivateKey: 
  dkimPublicKey: 
  email: 
  name: 

incidents:
  disableAutomaticCreation: false

statusPage: 
  cnameRecord: 

probes: 
  one: 
    name: "Probe"
    description: "Probe"
    monitoringWorkers: 3
    monitorFetchLimit: 10
  # two: 
  #   name: "Probe 2"
  #   description: "Probe 2"
  #   monitoringWorkers: 3
  #   monitorFetchLimit: 10

port: 
  app: 3002
  workflow: 3099
  alert: 3088
  ingestor: 3400
  testServer: 3800
  file: 3125
  identity: 3087
  notification: 3191
  realtime: 3300
  workers: 3452
  accounts: 3003
  statusPage: 3105
  dashboard: 3009
  adminDashboard: 3158
  nginx: 80
  haraka: 2525
  probe: 3500
  otelCollectorGrpc: 4317
  otelCollectorHttp: 4318


testServer: 
  enabled: false