global:
  storageClass: 


# Please change this to the domain name / IP where OneUtpime server is hosted on. 
host: localhost
httpProtocol: http

volume: 
  certs: 
    storage: 1Gi

deployment: 
  replicaCount: 1

metalLb: 
  enabled: false
  ipAdddressPool: 
    enabled: false
    addresses: 
      # - 51.158.55.153/32

ingress:
  service: 
    type: LoadBalancer
    loadBalancerIP: 

postgresql: 
  auth: 
    username: oneuptime
    database: oneuptimedb
  architecture: standalone
  primary:
    persistence:
      size: 25Gi
  readReplicas: 
    persistence:
      size: 25Gi

clickhouse: 
  shards: 1
  replicaCount: 1
  zookeeper: 
    enabled: false
  persistence: 
    size: 25Gi
  auth: 
    username: oneuptime
  initdbScripts: 
    db-init.sql: |
      CREATE DATABASE oneuptime;

redis: 
  architecture: standalone
  auth:
    enabled: true
  master:
    persistence:
      size: 25Gi
  replica:
    persistence:
      size: 25Gi
  

image:
  registry: docker.io
  repository: oneuptime
  pullPolicy: Always
  tag: release
  restartPolicy: Always

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeEnvironment: production

billing: 
  enabled: false
  publicKey: 
  privateKey: 
  smsDefaultValueInCents: 
  callDefaultValueInCentsPerMinute: 

subscriptionPlan: 
  basic: 
  growth: 
  scale: 
  enterprise: 

meteredPlan: 
  activeMonitoring: 

analytics: 
  host:
  key: 

internalSmtp: 
  sendingDomain: 
  dkimPrivateKey: 
  dkimPublicKey: 
  email: 
  name: 

incidents:
  disableAutomaticCreation: false

statusPage: 
  cnameRecord: 

probes: 
  one: 
    name: "Probe 1"
    description: "Probe 1"
    monitoringWorkers: 3
    monitorFetchLimit: 10
  two: 
    name: "Probe 2"
    description: "Probe 2"
    monitoringWorkers: 3
    monitorFetchLimit: 10

port: 
  home: 1444
  dashboardApi: 3002
  apiReference: 1445
  workflow: 3099
  linkShortener: 3521
  alert: 3088
  probeApi: 3400
  testServer: 3800
  file: 3125
  identity: 3087
  notification: 3191
  realtime: 3300
  workers: 3452
  accounts: 3003
  statusPage: 3105
  dashboard: 3009
  adminDashboard: 3158
  nginx: 80
  haraka: 2525


testServer: 
  enabled: false