apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $.Release.Name "secrets"  }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  internal-smtp: {{ randAlphaNum 32 | b64enc | quote }}
  oneuptime-secret: {{ randAlphaNum 32 | b64enc | quote }}
  encryption-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- range $key, $val := $.Values.probes }}
  {{printf "probe-%s" $key}}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}